/**
 * Bangladesh district and upazila names vendored from:
 * https://github.com/nuhil/bangladesh-geocode
 * Source revision: 5622f68bd07a98e076edcf8100bf0db6a75b9854
 * Files: districts/districts.json and upazilas/upazilas.json
 *
 * MIT License, Copyright (c) 2014 Nuhil Mehdy.
 * Only source IDs and trimmed Bangla/English names are retained; the
 * upazila district_id is represented by the grouping key below.
 */

export type LocationOption = { id: string; nameBn: string; nameEn: string };

export const DISTRICTS: LocationOption[] = [
  {"id":"1","nameBn":"কুমিল্লা","nameEn":"Comilla"},
  {"id":"2","nameBn":"ফেনী","nameEn":"Feni"},
  {"id":"3","nameBn":"ব্রাহ্মণবাড়িয়া","nameEn":"Brahmanbaria"},
  {"id":"4","nameBn":"রাঙ্গামাটি","nameEn":"Rangamati"},
  {"id":"5","nameBn":"নোয়াখালী","nameEn":"Noakhali"},
  {"id":"6","nameBn":"চাঁদপুর","nameEn":"Chandpur"},
  {"id":"7","nameBn":"লক্ষ্মীপুর","nameEn":"Lakshmipur"},
  {"id":"8","nameBn":"চট্টগ্রাম","nameEn":"Chattogram"},
  {"id":"9","nameBn":"কক্সবাজার","nameEn":"Coxsbazar"},
  {"id":"10","nameBn":"খাগড়াছড়ি","nameEn":"Khagrachhari"},
  {"id":"11","nameBn":"বান্দরবান","nameEn":"Bandarban"},
  {"id":"12","nameBn":"সিরাজগঞ্জ","nameEn":"Sirajganj"},
  {"id":"13","nameBn":"পাবনা","nameEn":"Pabna"},
  {"id":"14","nameBn":"বগুড়া","nameEn":"Bogura"},
  {"id":"15","nameBn":"রাজশাহী","nameEn":"Rajshahi"},
  {"id":"16","nameBn":"নাটোর","nameEn":"Natore"},
  {"id":"17","nameBn":"জয়পুরহাট","nameEn":"Joypurhat"},
  {"id":"18","nameBn":"চাঁপাইনবাবগঞ্জ","nameEn":"Chapainawabganj"},
  {"id":"19","nameBn":"নওগাঁ","nameEn":"Naogaon"},
  {"id":"20","nameBn":"যশোর","nameEn":"Jashore"},
  {"id":"21","nameBn":"সাতক্ষীরা","nameEn":"Satkhira"},
  {"id":"22","nameBn":"মেহেরপুর","nameEn":"Meherpur"},
  {"id":"23","nameBn":"নড়াইল","nameEn":"Narail"},
  {"id":"24","nameBn":"চুয়াডাঙ্গা","nameEn":"Chuadanga"},
  {"id":"25","nameBn":"কুষ্টিয়া","nameEn":"Kushtia"},
  {"id":"26","nameBn":"মাগুরা","nameEn":"Magura"},
  {"id":"27","nameBn":"খুলনা","nameEn":"Khulna"},
  {"id":"28","nameBn":"বাগেরহাট","nameEn":"Bagerhat"},
  {"id":"29","nameBn":"ঝিনাইদহ","nameEn":"Jhenaidah"},
  {"id":"30","nameBn":"ঝালকাঠি","nameEn":"Jhalakathi"},
  {"id":"31","nameBn":"পটুয়াখালী","nameEn":"Patuakhali"},
  {"id":"32","nameBn":"পিরোজপুর","nameEn":"Pirojpur"},
  {"id":"33","nameBn":"বরিশাল","nameEn":"Barisal"},
  {"id":"34","nameBn":"ভোলা","nameEn":"Bhola"},
  {"id":"35","nameBn":"বরগুনা","nameEn":"Barguna"},
  {"id":"36","nameBn":"সিলেট","nameEn":"Sylhet"},
  {"id":"37","nameBn":"মৌলভীবাজার","nameEn":"Moulvibazar"},
  {"id":"38","nameBn":"হবিগঞ্জ","nameEn":"Habiganj"},
  {"id":"39","nameBn":"সুনামগঞ্জ","nameEn":"Sunamganj"},
  {"id":"40","nameBn":"নরসিংদী","nameEn":"Narsingdi"},
  {"id":"41","nameBn":"গাজীপুর","nameEn":"Gazipur"},
  {"id":"42","nameBn":"শরীয়তপুর","nameEn":"Shariatpur"},
  {"id":"43","nameBn":"নারায়ণগঞ্জ","nameEn":"Narayanganj"},
  {"id":"44","nameBn":"টাঙ্গাইল","nameEn":"Tangail"},
  {"id":"45","nameBn":"কিশোরগঞ্জ","nameEn":"Kishoreganj"},
  {"id":"46","nameBn":"মানিকগঞ্জ","nameEn":"Manikganj"},
  {"id":"47","nameBn":"ঢাকা","nameEn":"Dhaka"},
  {"id":"48","nameBn":"মুন্সিগঞ্জ","nameEn":"Munshiganj"},
  {"id":"49","nameBn":"রাজবাড়ী","nameEn":"Rajbari"},
  {"id":"50","nameBn":"মাদারীপুর","nameEn":"Madaripur"},
  {"id":"51","nameBn":"গোপালগঞ্জ","nameEn":"Gopalganj"},
  {"id":"52","nameBn":"ফরিদপুর","nameEn":"Faridpur"},
  {"id":"53","nameBn":"পঞ্চগড়","nameEn":"Panchagarh"},
  {"id":"54","nameBn":"দিনাজপুর","nameEn":"Dinajpur"},
  {"id":"55","nameBn":"লালমনিরহাট","nameEn":"Lalmonirhat"},
  {"id":"56","nameBn":"নীলফামারী","nameEn":"Nilphamari"},
  {"id":"57","nameBn":"গাইবান্ধা","nameEn":"Gaibandha"},
  {"id":"58","nameBn":"ঠাকুরগাঁও","nameEn":"Thakurgaon"},
  {"id":"59","nameBn":"রংপুর","nameEn":"Rangpur"},
  {"id":"60","nameBn":"কুড়িগ্রাম","nameEn":"Kurigram"},
  {"id":"61","nameBn":"শেরপুর","nameEn":"Sherpur"},
  {"id":"62","nameBn":"ময়মনসিংহ","nameEn":"Mymensingh"},
  {"id":"63","nameBn":"জামালপুর","nameEn":"Jamalpur"},
  {"id":"64","nameBn":"নেত্রকোণা","nameEn":"Netrokona"},
];

const UPAZILAS_BY_DISTRICT: Record<string, LocationOption[]> = {
  "1": [
    {"id":"1","nameBn":"দেবিদ্বার","nameEn":"Debidwar"},
    {"id":"2","nameBn":"বরুড়া","nameEn":"Barura"},
    {"id":"3","nameBn":"ব্রাহ্মণপাড়া","nameEn":"Brahmanpara"},
    {"id":"4","nameBn":"চান্দিনা","nameEn":"Chandina"},
    {"id":"5","nameBn":"চৌদ্দগ্রাম","nameEn":"Chauddagram"},
    {"id":"6","nameBn":"দাউদকান্দি","nameEn":"Daudkandi"},
    {"id":"7","nameBn":"হোমনা","nameEn":"Homna"},
    {"id":"8","nameBn":"লাকসাম","nameEn":"Laksam"},
    {"id":"9","nameBn":"মুরাদনগর","nameEn":"Muradnagar"},
    {"id":"10","nameBn":"নাঙ্গলকোট","nameEn":"Nangalkot"},
    {"id":"11","nameBn":"কুমিল্লা সদর","nameEn":"Comilla Sadar"},
    {"id":"12","nameBn":"মেঘনা","nameEn":"Meghna"},
    {"id":"13","nameBn":"মনোহরগঞ্জ","nameEn":"Monohargonj"},
    {"id":"14","nameBn":"সদর দক্ষিণ","nameEn":"Sadarsouth"},
    {"id":"15","nameBn":"তিতাস","nameEn":"Titas"},
    {"id":"16","nameBn":"বুড়িচং","nameEn":"Burichang"},
    {"id":"17","nameBn":"লালমাই","nameEn":"Lalmai"},
  ],
  "2": [
    {"id":"18","nameBn":"ছাগলনাইয়া","nameEn":"Chhagalnaiya"},
    {"id":"19","nameBn":"ফেনী সদর","nameEn":"Feni Sadar"},
    {"id":"20","nameBn":"সোনাগাজী","nameEn":"Sonagazi"},
    {"id":"21","nameBn":"ফুলগাজী","nameEn":"Fulgazi"},
    {"id":"22","nameBn":"পরশুরাম","nameEn":"Parshuram"},
    {"id":"23","nameBn":"দাগনভূঞা","nameEn":"Daganbhuiyan"},
  ],
  "3": [
    {"id":"24","nameBn":"ব্রাহ্মণবাড়িয়া সদর","nameEn":"Brahmanbaria Sadar"},
    {"id":"25","nameBn":"কসবা","nameEn":"Kasba"},
    {"id":"26","nameBn":"নাসিরনগর","nameEn":"Nasirnagar"},
    {"id":"27","nameBn":"সরাইল","nameEn":"Sarail"},
    {"id":"28","nameBn":"আশুগঞ্জ","nameEn":"Ashuganj"},
    {"id":"29","nameBn":"আখাউড়া","nameEn":"Akhaura"},
    {"id":"30","nameBn":"নবীনগর","nameEn":"Nabinagar"},
    {"id":"31","nameBn":"বাঞ্ছারামপুর","nameEn":"Bancharampur"},
    {"id":"32","nameBn":"বিজয়নগর","nameEn":"Bijoynagar"},
  ],
  "4": [
    {"id":"33","nameBn":"রাঙ্গামাটি সদর","nameEn":"Rangamati Sadar"},
    {"id":"34","nameBn":"কাপ্তাই","nameEn":"Kaptai"},
    {"id":"35","nameBn":"কাউখালী","nameEn":"Kawkhali"},
    {"id":"36","nameBn":"বাঘাইছড়ি","nameEn":"Baghaichari"},
    {"id":"37","nameBn":"বরকল","nameEn":"Barkal"},
    {"id":"38","nameBn":"লংগদু","nameEn":"Langadu"},
    {"id":"39","nameBn":"রাজস্থলী","nameEn":"Rajasthali"},
    {"id":"40","nameBn":"বিলাইছড়ি","nameEn":"Belaichari"},
    {"id":"41","nameBn":"জুরাছড়ি","nameEn":"Juraichari"},
    {"id":"42","nameBn":"নানিয়ারচর","nameEn":"Naniarchar"},
  ],
  "5": [
    {"id":"43","nameBn":"নোয়াখালী সদর","nameEn":"Noakhali Sadar"},
    {"id":"44","nameBn":"কোম্পানীগঞ্জ","nameEn":"Companiganj"},
    {"id":"45","nameBn":"বেগমগঞ্জ","nameEn":"Begumganj"},
    {"id":"46","nameBn":"হাতিয়া","nameEn":"Hatia"},
    {"id":"47","nameBn":"সুবর্ণচর","nameEn":"Subarnachar"},
    {"id":"48","nameBn":"কবিরহাট","nameEn":"Kabirhat"},
    {"id":"49","nameBn":"সেনবাগ","nameEn":"Senbug"},
    {"id":"50","nameBn":"চাটখিল","nameEn":"Chatkhil"},
    {"id":"51","nameBn":"সোনাইমুড়ী","nameEn":"Sonaimori"},
  ],
  "6": [
    {"id":"52","nameBn":"হাইমচর","nameEn":"Haimchar"},
    {"id":"53","nameBn":"কচুয়া","nameEn":"Kachua"},
    {"id":"54","nameBn":"শাহরাস্তি","nameEn":"Shahrasti"},
    {"id":"55","nameBn":"চাঁদপুর সদর","nameEn":"Chandpur Sadar"},
    {"id":"56","nameBn":"মতলব দক্ষিণ","nameEn":"Matlab South"},
    {"id":"57","nameBn":"হাজীগঞ্জ","nameEn":"Hajiganj"},
    {"id":"58","nameBn":"মতলব উত্তর","nameEn":"Matlab North"},
    {"id":"59","nameBn":"ফরিদগঞ্জ","nameEn":"Faridgonj"},
  ],
  "7": [
    {"id":"60","nameBn":"লক্ষ্মীপুর সদর","nameEn":"Lakshmipur Sadar"},
    {"id":"61","nameBn":"কমলনগর","nameEn":"Kamalnagar"},
    {"id":"62","nameBn":"রায়পুর","nameEn":"Raipur"},
    {"id":"63","nameBn":"রামগতি","nameEn":"Ramgati"},
    {"id":"64","nameBn":"রামগঞ্জ","nameEn":"Ramganj"},
  ],
  "8": [
    {"id":"65","nameBn":"রাঙ্গুনিয়া","nameEn":"Rangunia"},
    {"id":"66","nameBn":"সীতাকুন্ড","nameEn":"Sitakunda"},
    {"id":"67","nameBn":"মীরসরাই","nameEn":"Mirsharai"},
    {"id":"68","nameBn":"পটিয়া","nameEn":"Patiya"},
    {"id":"69","nameBn":"সন্দ্বীপ","nameEn":"Sandwip"},
    {"id":"70","nameBn":"বাঁশখালী","nameEn":"Banshkhali"},
    {"id":"71","nameBn":"বোয়ালখালী","nameEn":"Boalkhali"},
    {"id":"72","nameBn":"আনোয়ারা","nameEn":"Anwara"},
    {"id":"73","nameBn":"চন্দনাইশ","nameEn":"Chandanaish"},
    {"id":"74","nameBn":"সাতকানিয়া","nameEn":"Satkania"},
    {"id":"75","nameBn":"লোহাগাড়া","nameEn":"Lohagara"},
    {"id":"76","nameBn":"হাটহাজারী","nameEn":"Hathazari"},
    {"id":"77","nameBn":"ফটিকছড়ি","nameEn":"Fatikchhari"},
    {"id":"78","nameBn":"রাউজান","nameEn":"Raozan"},
    {"id":"79","nameBn":"কর্ণফুলী","nameEn":"Karnafuli"},
  ],
  "9": [
    {"id":"80","nameBn":"কক্সবাজার সদর","nameEn":"Coxsbazar Sadar"},
    {"id":"81","nameBn":"চকরিয়া","nameEn":"Chakaria"},
    {"id":"82","nameBn":"কুতুবদিয়া","nameEn":"Kutubdia"},
    {"id":"83","nameBn":"উখিয়া","nameEn":"Ukhiya"},
    {"id":"84","nameBn":"মহেশখালী","nameEn":"Moheshkhali"},
    {"id":"85","nameBn":"পেকুয়া","nameEn":"Pekua"},
    {"id":"86","nameBn":"রামু","nameEn":"Ramu"},
    {"id":"87","nameBn":"টেকনাফ","nameEn":"Teknaf"},
    {"id":"492","nameBn":"ঈদগাঁও","nameEn":"Eidgaon"},
  ],
  "10": [
    {"id":"88","nameBn":"খাগড়াছড়ি সদর","nameEn":"Khagrachhari Sadar"},
    {"id":"89","nameBn":"দিঘীনালা","nameEn":"Dighinala"},
    {"id":"90","nameBn":"পানছড়ি","nameEn":"Panchari"},
    {"id":"91","nameBn":"লক্ষীছড়ি","nameEn":"Laxmichhari"},
    {"id":"92","nameBn":"মহালছড়ি","nameEn":"Mohalchari"},
    {"id":"93","nameBn":"মানিকছড়ি","nameEn":"Manikchari"},
    {"id":"94","nameBn":"রামগড়","nameEn":"Ramgarh"},
    {"id":"95","nameBn":"মাটিরাঙ্গা","nameEn":"Matiranga"},
    {"id":"96","nameBn":"গুইমারা","nameEn":"Guimara"},
  ],
  "11": [
    {"id":"97","nameBn":"বান্দরবান সদর","nameEn":"Bandarban Sadar"},
    {"id":"98","nameBn":"আলীকদম","nameEn":"Alikadam"},
    {"id":"99","nameBn":"নাইক্ষ্যংছড়ি","nameEn":"Naikhongchhari"},
    {"id":"100","nameBn":"রোয়াংছড়ি","nameEn":"Rowangchhari"},
    {"id":"101","nameBn":"লামা","nameEn":"Lama"},
    {"id":"102","nameBn":"রুমা","nameEn":"Ruma"},
    {"id":"103","nameBn":"থানচি","nameEn":"Thanchi"},
  ],
  "12": [
    {"id":"104","nameBn":"বেলকুচি","nameEn":"Belkuchi"},
    {"id":"105","nameBn":"চৌহালি","nameEn":"Chauhali"},
    {"id":"106","nameBn":"কামারখন্দ","nameEn":"Kamarkhand"},
    {"id":"107","nameBn":"কাজীপুর","nameEn":"Kazipur"},
    {"id":"108","nameBn":"রায়গঞ্জ","nameEn":"Raigonj"},
    {"id":"109","nameBn":"শাহজাদপুর","nameEn":"Shahjadpur"},
    {"id":"110","nameBn":"সিরাজগঞ্জ সদর","nameEn":"Sirajganj Sadar"},
    {"id":"111","nameBn":"তাড়াশ","nameEn":"Tarash"},
    {"id":"112","nameBn":"উল্লাপাড়া","nameEn":"Ullapara"},
  ],
  "13": [
    {"id":"113","nameBn":"সুজানগর","nameEn":"Sujanagar"},
    {"id":"114","nameBn":"ঈশ্বরদী","nameEn":"Ishurdi"},
    {"id":"115","nameBn":"ভাঙ্গুড়া","nameEn":"Bhangura"},
    {"id":"116","nameBn":"পাবনা সদর","nameEn":"Pabna Sadar"},
    {"id":"117","nameBn":"বেড়া","nameEn":"Bera"},
    {"id":"118","nameBn":"আটঘরিয়া","nameEn":"Atghoria"},
    {"id":"119","nameBn":"চাটমোহর","nameEn":"Chatmohar"},
    {"id":"120","nameBn":"সাঁথিয়া","nameEn":"Santhia"},
    {"id":"121","nameBn":"ফরিদপুর","nameEn":"Faridpur"},
  ],
  "14": [
    {"id":"122","nameBn":"কাহালু","nameEn":"Kahaloo"},
    {"id":"123","nameBn":"বগুড়া সদর","nameEn":"Bogra Sadar"},
    {"id":"124","nameBn":"সারিয়াকান্দি","nameEn":"Shariakandi"},
    {"id":"125","nameBn":"শাজাহানপুর","nameEn":"Shajahanpur"},
    {"id":"126","nameBn":"দুপচাচিঁয়া","nameEn":"Dupchanchia"},
    {"id":"127","nameBn":"আদমদিঘি","nameEn":"Adamdighi"},
    {"id":"128","nameBn":"নন্দিগ্রাম","nameEn":"Nondigram"},
    {"id":"129","nameBn":"সোনাতলা","nameEn":"Sonatala"},
    {"id":"130","nameBn":"ধুনট","nameEn":"Dhunot"},
    {"id":"131","nameBn":"গাবতলী","nameEn":"Gabtali"},
    {"id":"132","nameBn":"শেরপুর","nameEn":"Sherpur"},
    {"id":"133","nameBn":"শিবগঞ্জ","nameEn":"Shibganj"},
  ],
  "15": [
    {"id":"134","nameBn":"পবা","nameEn":"Paba"},
    {"id":"135","nameBn":"দুর্গাপুর","nameEn":"Durgapur"},
    {"id":"136","nameBn":"মোহনপুর","nameEn":"Mohonpur"},
    {"id":"137","nameBn":"চারঘাট","nameEn":"Charghat"},
    {"id":"138","nameBn":"পুঠিয়া","nameEn":"Puthia"},
    {"id":"139","nameBn":"বাঘা","nameEn":"Bagha"},
    {"id":"140","nameBn":"গোদাগাড়ী","nameEn":"Godagari"},
    {"id":"141","nameBn":"তানোর","nameEn":"Tanore"},
    {"id":"142","nameBn":"বাগমারা","nameEn":"Bagmara"},
  ],
  "16": [
    {"id":"143","nameBn":"নাটোর সদর","nameEn":"Natore Sadar"},
    {"id":"144","nameBn":"সিংড়া","nameEn":"Singra"},
    {"id":"145","nameBn":"বড়াইগ্রাম","nameEn":"Baraigram"},
    {"id":"146","nameBn":"বাগাতিপাড়া","nameEn":"Bagatipara"},
    {"id":"147","nameBn":"লালপুর","nameEn":"Lalpur"},
    {"id":"148","nameBn":"গুরুদাসপুর","nameEn":"Gurudaspur"},
    {"id":"149","nameBn":"নলডাঙ্গা","nameEn":"Naldanga"},
  ],
  "17": [
    {"id":"150","nameBn":"আক্কেলপুর","nameEn":"Akkelpur"},
    {"id":"151","nameBn":"কালাই","nameEn":"Kalai"},
    {"id":"152","nameBn":"ক্ষেতলাল","nameEn":"Khetlal"},
    {"id":"153","nameBn":"পাঁচবিবি","nameEn":"Panchbibi"},
    {"id":"154","nameBn":"জয়পুরহাট সদর","nameEn":"Joypurhat Sadar"},
  ],
  "18": [
    {"id":"155","nameBn":"চাঁপাইনবাবগঞ্জ সদর","nameEn":"Chapainawabganj Sadar"},
    {"id":"156","nameBn":"গোমস্তাপুর","nameEn":"Gomostapur"},
    {"id":"157","nameBn":"নাচোল","nameEn":"Nachol"},
    {"id":"158","nameBn":"ভোলাহাট","nameEn":"Bholahat"},
    {"id":"159","nameBn":"শিবগঞ্জ","nameEn":"Shibganj"},
  ],
  "19": [
    {"id":"160","nameBn":"মহাদেবপুর","nameEn":"Mohadevpur"},
    {"id":"161","nameBn":"বদলগাছী","nameEn":"Badalgachi"},
    {"id":"162","nameBn":"পত্নিতলা","nameEn":"Patnitala"},
    {"id":"163","nameBn":"ধামইরহাট","nameEn":"Dhamoirhat"},
    {"id":"164","nameBn":"নিয়ামতপুর","nameEn":"Niamatpur"},
    {"id":"165","nameBn":"মান্দা","nameEn":"Manda"},
    {"id":"166","nameBn":"আত্রাই","nameEn":"Atrai"},
    {"id":"167","nameBn":"রাণীনগর","nameEn":"Raninagar"},
    {"id":"168","nameBn":"নওগাঁ সদর","nameEn":"Naogaon Sadar"},
    {"id":"169","nameBn":"পোরশা","nameEn":"Porsha"},
    {"id":"170","nameBn":"সাপাহার","nameEn":"Sapahar"},
  ],
  "20": [
    {"id":"171","nameBn":"মণিরামপুর","nameEn":"Manirampur"},
    {"id":"172","nameBn":"অভয়নগর","nameEn":"Abhaynagar"},
    {"id":"173","nameBn":"বাঘারপাড়া","nameEn":"Bagherpara"},
    {"id":"174","nameBn":"চৌগাছা","nameEn":"Chougachha"},
    {"id":"175","nameBn":"ঝিকরগাছা","nameEn":"Jhikargacha"},
    {"id":"176","nameBn":"কেশবপুর","nameEn":"Keshabpur"},
    {"id":"177","nameBn":"যশোর সদর","nameEn":"Jessore Sadar"},
    {"id":"178","nameBn":"শার্শা","nameEn":"Sharsha"},
  ],
  "21": [
    {"id":"179","nameBn":"আশাশুনি","nameEn":"Assasuni"},
    {"id":"180","nameBn":"দেবহাটা","nameEn":"Debhata"},
    {"id":"181","nameBn":"কলারোয়া","nameEn":"Kalaroa"},
    {"id":"182","nameBn":"সাতক্ষীরা সদর","nameEn":"Satkhira Sadar"},
    {"id":"183","nameBn":"শ্যামনগর","nameEn":"Shyamnagar"},
    {"id":"184","nameBn":"তালা","nameEn":"Tala"},
    {"id":"185","nameBn":"কালিগঞ্জ","nameEn":"Kaliganj"},
  ],
  "22": [
    {"id":"186","nameBn":"মুজিবনগর","nameEn":"Mujibnagar"},
    {"id":"187","nameBn":"মেহেরপুর সদর","nameEn":"Meherpur Sadar"},
    {"id":"188","nameBn":"গাংনী","nameEn":"Gangni"},
  ],
  "23": [
    {"id":"189","nameBn":"নড়াইল সদর","nameEn":"Narail Sadar"},
    {"id":"190","nameBn":"লোহাগড়া","nameEn":"Lohagara"},
    {"id":"191","nameBn":"কালিয়া","nameEn":"Kalia"},
  ],
  "24": [
    {"id":"192","nameBn":"চুয়াডাঙ্গা সদর","nameEn":"Chuadanga Sadar"},
    {"id":"193","nameBn":"আলমডাঙ্গা","nameEn":"Alamdanga"},
    {"id":"194","nameBn":"দামুড়হুদা","nameEn":"Damurhuda"},
    {"id":"195","nameBn":"জীবননগর","nameEn":"Jibannagar"},
  ],
  "25": [
    {"id":"196","nameBn":"কুষ্টিয়া সদর","nameEn":"Kushtia Sadar"},
    {"id":"197","nameBn":"কুমারখালী","nameEn":"Kumarkhali"},
    {"id":"198","nameBn":"খোকসা","nameEn":"Khoksa"},
    {"id":"199","nameBn":"মিরপুর","nameEn":"Mirpur"},
    {"id":"200","nameBn":"দৌলতপুর","nameEn":"Daulatpur"},
    {"id":"201","nameBn":"ভেড়ামারা","nameEn":"Bheramara"},
  ],
  "26": [
    {"id":"202","nameBn":"শালিখা","nameEn":"Shalikha"},
    {"id":"203","nameBn":"শ্রীপুর","nameEn":"Sreepur"},
    {"id":"204","nameBn":"মাগুরা সদর","nameEn":"Magura Sadar"},
    {"id":"205","nameBn":"মহম্মদপুর","nameEn":"Mohammadpur"},
  ],
  "27": [
    {"id":"206","nameBn":"পাইকগাছা","nameEn":"Paikgasa"},
    {"id":"207","nameBn":"ফুলতলা","nameEn":"Fultola"},
    {"id":"208","nameBn":"দিঘলিয়া","nameEn":"Digholia"},
    {"id":"209","nameBn":"রূপসা","nameEn":"Rupsha"},
    {"id":"210","nameBn":"তেরখাদা","nameEn":"Terokhada"},
    {"id":"211","nameBn":"ডুমুরিয়া","nameEn":"Dumuria"},
    {"id":"212","nameBn":"বটিয়াঘাটা","nameEn":"Botiaghata"},
    {"id":"213","nameBn":"দাকোপ","nameEn":"Dakop"},
    {"id":"214","nameBn":"কয়রা","nameEn":"Koyra"},
  ],
  "28": [
    {"id":"215","nameBn":"ফকিরহাট","nameEn":"Fakirhat"},
    {"id":"216","nameBn":"বাগেরহাট সদর","nameEn":"Bagerhat Sadar"},
    {"id":"217","nameBn":"মোল্লাহাট","nameEn":"Mollahat"},
    {"id":"218","nameBn":"শরণখোলা","nameEn":"Sarankhola"},
    {"id":"219","nameBn":"রামপাল","nameEn":"Rampal"},
    {"id":"220","nameBn":"মোড়েলগঞ্জ","nameEn":"Morrelganj"},
    {"id":"221","nameBn":"কচুয়া","nameEn":"Kachua"},
    {"id":"222","nameBn":"মোংলা","nameEn":"Mongla"},
    {"id":"223","nameBn":"চিতলমারী","nameEn":"Chitalmari"},
  ],
  "29": [
    {"id":"224","nameBn":"ঝিনাইদহ সদর","nameEn":"Jhenaidah Sadar"},
    {"id":"225","nameBn":"শৈলকুপা","nameEn":"Shailkupa"},
    {"id":"226","nameBn":"হরিণাকুন্ডু","nameEn":"Harinakundu"},
    {"id":"227","nameBn":"কালীগঞ্জ","nameEn":"Kaliganj"},
    {"id":"228","nameBn":"কোটচাঁদপুর","nameEn":"Kotchandpur"},
    {"id":"229","nameBn":"মহেশপুর","nameEn":"Moheshpur"},
  ],
  "30": [
    {"id":"230","nameBn":"ঝালকাঠি সদর","nameEn":"Jhalakathi Sadar"},
    {"id":"231","nameBn":"কাঠালিয়া","nameEn":"Kathalia"},
    {"id":"232","nameBn":"নলছিটি","nameEn":"Nalchity"},
    {"id":"233","nameBn":"রাজাপুর","nameEn":"Rajapur"},
  ],
  "31": [
    {"id":"234","nameBn":"বাউফল","nameEn":"Bauphal"},
    {"id":"235","nameBn":"পটুয়াখালী সদর","nameEn":"Patuakhali Sadar"},
    {"id":"236","nameBn":"দুমকি","nameEn":"Dumki"},
    {"id":"237","nameBn":"দশমিনা","nameEn":"Dashmina"},
    {"id":"238","nameBn":"কলাপাড়া","nameEn":"Kalapara"},
    {"id":"239","nameBn":"মির্জাগঞ্জ","nameEn":"Mirzaganj"},
    {"id":"240","nameBn":"গলাচিপা","nameEn":"Galachipa"},
    {"id":"241","nameBn":"রাঙ্গাবালী","nameEn":"Rangabali"},
  ],
  "32": [
    {"id":"242","nameBn":"পিরোজপুর সদর","nameEn":"Pirojpur Sadar"},
    {"id":"243","nameBn":"নাজিরপুর","nameEn":"Nazirpur"},
    {"id":"244","nameBn":"কাউখালী","nameEn":"Kawkhali"},
    {"id":"245","nameBn":"জিয়ানগর","nameEn":"Zianagar"},
    {"id":"246","nameBn":"ভান্ডারিয়া","nameEn":"Bhandaria"},
    {"id":"247","nameBn":"মঠবাড়ীয়া","nameEn":"Mathbaria"},
    {"id":"248","nameBn":"নেছারাবাদ","nameEn":"Nesarabad"},
  ],
  "33": [
    {"id":"249","nameBn":"বরিশাল সদর","nameEn":"Barisal Sadar"},
    {"id":"250","nameBn":"বাকেরগঞ্জ","nameEn":"Bakerganj"},
    {"id":"251","nameBn":"বাবুগঞ্জ","nameEn":"Babuganj"},
    {"id":"252","nameBn":"উজিরপুর","nameEn":"Wazirpur"},
    {"id":"253","nameBn":"বানারীপাড়া","nameEn":"Banaripara"},
    {"id":"254","nameBn":"গৌরনদী","nameEn":"Gournadi"},
    {"id":"255","nameBn":"আগৈলঝাড়া","nameEn":"Agailjhara"},
    {"id":"256","nameBn":"মেহেন্দিগঞ্জ","nameEn":"Mehendiganj"},
    {"id":"257","nameBn":"মুলাদী","nameEn":"Muladi"},
    {"id":"258","nameBn":"হিজলা","nameEn":"Hizla"},
  ],
  "34": [
    {"id":"259","nameBn":"ভোলা সদর","nameEn":"Bhola Sadar"},
    {"id":"260","nameBn":"বোরহান উদ্দিন","nameEn":"Borhan Sddin"},
    {"id":"261","nameBn":"চরফ্যাশন","nameEn":"Charfesson"},
    {"id":"262","nameBn":"দৌলতখান","nameEn":"Doulatkhan"},
    {"id":"263","nameBn":"মনপুরা","nameEn":"Monpura"},
    {"id":"264","nameBn":"তজুমদ্দিন","nameEn":"Tazumuddin"},
    {"id":"265","nameBn":"লালমোহন","nameEn":"Lalmohan"},
  ],
  "35": [
    {"id":"266","nameBn":"আমতলী","nameEn":"Amtali"},
    {"id":"267","nameBn":"বরগুনা সদর","nameEn":"Barguna Sadar"},
    {"id":"268","nameBn":"বেতাগী","nameEn":"Betagi"},
    {"id":"269","nameBn":"বামনা","nameEn":"Bamna"},
    {"id":"270","nameBn":"পাথরঘাটা","nameEn":"Pathorghata"},
    {"id":"271","nameBn":"তালতলি","nameEn":"Taltali"},
  ],
  "36": [
    {"id":"272","nameBn":"বালাগঞ্জ","nameEn":"Balaganj"},
    {"id":"273","nameBn":"বিয়ানীবাজার","nameEn":"Beanibazar"},
    {"id":"274","nameBn":"বিশ্বনাথ","nameEn":"Bishwanath"},
    {"id":"275","nameBn":"কোম্পানীগঞ্জ","nameEn":"Companiganj"},
    {"id":"276","nameBn":"ফেঞ্চুগঞ্জ","nameEn":"Fenchuganj"},
    {"id":"277","nameBn":"গোলাপগঞ্জ","nameEn":"Golapganj"},
    {"id":"278","nameBn":"গোয়াইনঘাট","nameEn":"Gowainghat"},
    {"id":"279","nameBn":"জৈন্তাপুর","nameEn":"Jaintiapur"},
    {"id":"280","nameBn":"কানাইঘাট","nameEn":"Kanaighat"},
    {"id":"281","nameBn":"সিলেট সদর","nameEn":"Sylhet Sadar"},
    {"id":"282","nameBn":"জকিগঞ্জ","nameEn":"Zakiganj"},
    {"id":"283","nameBn":"দক্ষিণ সুরমা","nameEn":"Dakshinsurma"},
    {"id":"284","nameBn":"ওসমানী নগর","nameEn":"Osmaninagar"},
  ],
  "37": [
    {"id":"285","nameBn":"বড়লেখা","nameEn":"Barlekha"},
    {"id":"286","nameBn":"কমলগঞ্জ","nameEn":"Kamolganj"},
    {"id":"287","nameBn":"কুলাউড়া","nameEn":"Kulaura"},
    {"id":"288","nameBn":"মৌলভীবাজার সদর","nameEn":"Moulvibazar Sadar"},
    {"id":"289","nameBn":"রাজনগর","nameEn":"Rajnagar"},
    {"id":"290","nameBn":"শ্রীমঙ্গল","nameEn":"Sreemangal"},
    {"id":"291","nameBn":"জুড়ী","nameEn":"Juri"},
  ],
  "38": [
    {"id":"292","nameBn":"নবীগঞ্জ","nameEn":"Nabiganj"},
    {"id":"293","nameBn":"বাহুবল","nameEn":"Bahubal"},
    {"id":"294","nameBn":"আজমিরীগঞ্জ","nameEn":"Ajmiriganj"},
    {"id":"295","nameBn":"বানিয়াচং","nameEn":"Baniachong"},
    {"id":"296","nameBn":"লাখাই","nameEn":"Lakhai"},
    {"id":"297","nameBn":"চুনারুঘাট","nameEn":"Chunarughat"},
    {"id":"298","nameBn":"হবিগঞ্জ সদর","nameEn":"Habiganj Sadar"},
    {"id":"299","nameBn":"মাধবপুর","nameEn":"Madhabpur"},
  ],
  "39": [
    {"id":"300","nameBn":"সুনামগঞ্জ সদর","nameEn":"Sunamganj Sadar"},
    {"id":"301","nameBn":"দক্ষিণ সুনামগঞ্জ","nameEn":"South Sunamganj"},
    {"id":"302","nameBn":"বিশ্বম্ভরপুর","nameEn":"Bishwambarpur"},
    {"id":"303","nameBn":"ছাতক","nameEn":"Chhatak"},
    {"id":"304","nameBn":"জগন্নাথপুর","nameEn":"Jagannathpur"},
    {"id":"305","nameBn":"দোয়ারাবাজার","nameEn":"Dowarabazar"},
    {"id":"306","nameBn":"তাহিরপুর","nameEn":"Tahirpur"},
    {"id":"307","nameBn":"ধর্মপাশা","nameEn":"Dharmapasha"},
    {"id":"308","nameBn":"জামালগঞ্জ","nameEn":"Jamalganj"},
    {"id":"309","nameBn":"শাল্লা","nameEn":"Shalla"},
    {"id":"310","nameBn":"দিরাই","nameEn":"Derai"},
    {"id":"493","nameBn":"মধ্যনগর","nameEn":"Madhyanagar"},
  ],
  "40": [
    {"id":"311","nameBn":"বেলাবো","nameEn":"Belabo"},
    {"id":"312","nameBn":"মনোহরদী","nameEn":"Monohardi"},
    {"id":"313","nameBn":"নরসিংদী সদর","nameEn":"Narsingdi Sadar"},
    {"id":"314","nameBn":"পলাশ","nameEn":"Palash"},
    {"id":"315","nameBn":"রায়পুরা","nameEn":"Raipura"},
    {"id":"316","nameBn":"শিবপুর","nameEn":"Shibpur"},
  ],
  "41": [
    {"id":"317","nameBn":"কালীগঞ্জ","nameEn":"Kaliganj"},
    {"id":"318","nameBn":"কালিয়াকৈর","nameEn":"Kaliakair"},
    {"id":"319","nameBn":"কাপাসিয়া","nameEn":"Kapasia"},
    {"id":"320","nameBn":"গাজীপুর সদর","nameEn":"Gazipur Sadar"},
    {"id":"321","nameBn":"শ্রীপুর","nameEn":"Sreepur"},
  ],
  "42": [
    {"id":"322","nameBn":"শরিয়তপুর সদর","nameEn":"Shariatpur Sadar"},
    {"id":"323","nameBn":"নড়িয়া","nameEn":"Naria"},
    {"id":"324","nameBn":"জাজিরা","nameEn":"Zajira"},
    {"id":"325","nameBn":"গোসাইরহাট","nameEn":"Gosairhat"},
    {"id":"326","nameBn":"ভেদরগঞ্জ","nameEn":"Bhedarganj"},
    {"id":"327","nameBn":"ডামুড্যা","nameEn":"Damudya"},
  ],
  "43": [
    {"id":"328","nameBn":"আড়াইহাজার","nameEn":"Araihazar"},
    {"id":"329","nameBn":"বন্দর","nameEn":"Bandar"},
    {"id":"330","nameBn":"নারায়নগঞ্জ সদর","nameEn":"Narayanganj Sadar"},
    {"id":"331","nameBn":"রূপগঞ্জ","nameEn":"Rupganj"},
    {"id":"332","nameBn":"সোনারগাঁ","nameEn":"Sonargaon"},
  ],
  "44": [
    {"id":"333","nameBn":"বাসাইল","nameEn":"Basail"},
    {"id":"334","nameBn":"ভুয়াপুর","nameEn":"Bhuapur"},
    {"id":"335","nameBn":"দেলদুয়ার","nameEn":"Delduar"},
    {"id":"336","nameBn":"ঘাটাইল","nameEn":"Ghatail"},
    {"id":"337","nameBn":"গোপালপুর","nameEn":"Gopalpur"},
    {"id":"338","nameBn":"মধুপুর","nameEn":"Madhupur"},
    {"id":"339","nameBn":"মির্জাপুর","nameEn":"Mirzapur"},
    {"id":"340","nameBn":"নাগরপুর","nameEn":"Nagarpur"},
    {"id":"341","nameBn":"সখিপুর","nameEn":"Sakhipur"},
    {"id":"342","nameBn":"টাঙ্গাইল সদর","nameEn":"Tangail Sadar"},
    {"id":"343","nameBn":"কালিহাতী","nameEn":"Kalihati"},
    {"id":"344","nameBn":"ধনবাড়ী","nameEn":"Dhanbari"},
  ],
  "45": [
    {"id":"345","nameBn":"ইটনা","nameEn":"Itna"},
    {"id":"346","nameBn":"কটিয়াদী","nameEn":"Katiadi"},
    {"id":"347","nameBn":"ভৈরব","nameEn":"Bhairab"},
    {"id":"348","nameBn":"তাড়াইল","nameEn":"Tarail"},
    {"id":"349","nameBn":"হোসেনপুর","nameEn":"Hossainpur"},
    {"id":"350","nameBn":"পাকুন্দিয়া","nameEn":"Pakundia"},
    {"id":"351","nameBn":"কুলিয়ারচর","nameEn":"Kuliarchar"},
    {"id":"352","nameBn":"কিশোরগঞ্জ সদর","nameEn":"Kishoreganj Sadar"},
    {"id":"353","nameBn":"করিমগঞ্জ","nameEn":"Karimgonj"},
    {"id":"354","nameBn":"বাজিতপুর","nameEn":"Bajitpur"},
    {"id":"355","nameBn":"অষ্টগ্রাম","nameEn":"Austagram"},
    {"id":"356","nameBn":"মিঠামইন","nameEn":"Mithamoin"},
    {"id":"357","nameBn":"নিকলী","nameEn":"Nikli"},
  ],
  "46": [
    {"id":"358","nameBn":"হরিরামপুর","nameEn":"Harirampur"},
    {"id":"359","nameBn":"সাটুরিয়া","nameEn":"Saturia"},
    {"id":"360","nameBn":"মানিকগঞ্জ সদর","nameEn":"Manikganj Sadar"},
    {"id":"361","nameBn":"ঘিওর","nameEn":"Gior"},
    {"id":"362","nameBn":"শিবালয়","nameEn":"Shibaloy"},
    {"id":"363","nameBn":"দৌলতপুর","nameEn":"Doulatpur"},
    {"id":"364","nameBn":"সিংগাইর","nameEn":"Singiar"},
  ],
  "47": [
    {"id":"365","nameBn":"সাভার","nameEn":"Savar"},
    {"id":"366","nameBn":"ধামরাই","nameEn":"Dhamrai"},
    {"id":"367","nameBn":"কেরাণীগঞ্জ","nameEn":"Keraniganj"},
    {"id":"368","nameBn":"নবাবগঞ্জ","nameEn":"Nawabganj"},
    {"id":"369","nameBn":"দোহার","nameEn":"Dohar"},
  ],
  "48": [
    {"id":"370","nameBn":"মুন্সিগঞ্জ সদর","nameEn":"Munshiganj Sadar"},
    {"id":"371","nameBn":"শ্রীনগর","nameEn":"Sreenagar"},
    {"id":"372","nameBn":"সিরাজদিখান","nameEn":"Sirajdikhan"},
    {"id":"373","nameBn":"লৌহজং","nameEn":"Louhajanj"},
    {"id":"374","nameBn":"গজারিয়া","nameEn":"Gajaria"},
    {"id":"375","nameBn":"টংগীবাড়ি","nameEn":"Tongibari"},
  ],
  "49": [
    {"id":"376","nameBn":"রাজবাড়ী সদর","nameEn":"Rajbari Sadar"},
    {"id":"377","nameBn":"গোয়ালন্দ","nameEn":"Goalanda"},
    {"id":"378","nameBn":"পাংশা","nameEn":"Pangsa"},
    {"id":"379","nameBn":"বালিয়াকান্দি","nameEn":"Baliakandi"},
    {"id":"380","nameBn":"কালুখালী","nameEn":"Kalukhali"},
  ],
  "50": [
    {"id":"381","nameBn":"মাদারীপুর সদর","nameEn":"Madaripur Sadar"},
    {"id":"382","nameBn":"শিবচর","nameEn":"Shibchar"},
    {"id":"383","nameBn":"কালকিনি","nameEn":"Kalkini"},
    {"id":"384","nameBn":"রাজৈর","nameEn":"Rajoir"},
    {"id":"494","nameBn":"ডাসার","nameEn":"Dasar"},
  ],
  "51": [
    {"id":"385","nameBn":"গোপালগঞ্জ সদর","nameEn":"Gopalganj Sadar"},
    {"id":"386","nameBn":"কাশিয়ানী","nameEn":"Kashiani"},
    {"id":"387","nameBn":"টুংগীপাড়া","nameEn":"Tungipara"},
    {"id":"388","nameBn":"কোটালীপাড়া","nameEn":"Kotalipara"},
    {"id":"389","nameBn":"মুকসুদপুর","nameEn":"Muksudpur"},
  ],
  "52": [
    {"id":"390","nameBn":"ফরিদপুর সদর","nameEn":"Faridpur Sadar"},
    {"id":"391","nameBn":"আলফাডাঙ্গা","nameEn":"Alfadanga"},
    {"id":"392","nameBn":"বোয়ালমারী","nameEn":"Boalmari"},
    {"id":"393","nameBn":"সদরপুর","nameEn":"Sadarpur"},
    {"id":"394","nameBn":"নগরকান্দা","nameEn":"Nagarkanda"},
    {"id":"395","nameBn":"ভাঙ্গা","nameEn":"Bhanga"},
    {"id":"396","nameBn":"চরভদ্রাসন","nameEn":"Charbhadrasan"},
    {"id":"397","nameBn":"মধুখালী","nameEn":"Madhukhali"},
    {"id":"398","nameBn":"সালথা","nameEn":"Saltha"},
  ],
  "53": [
    {"id":"399","nameBn":"পঞ্চগড় সদর","nameEn":"Panchagarh Sadar"},
    {"id":"400","nameBn":"দেবীগঞ্জ","nameEn":"Debiganj"},
    {"id":"401","nameBn":"বোদা","nameEn":"Boda"},
    {"id":"402","nameBn":"আটোয়ারী","nameEn":"Atwari"},
    {"id":"403","nameBn":"তেতুলিয়া","nameEn":"Tetulia"},
  ],
  "54": [
    {"id":"404","nameBn":"নবাবগঞ্জ","nameEn":"Nawabganj"},
    {"id":"405","nameBn":"বীরগঞ্জ","nameEn":"Birganj"},
    {"id":"406","nameBn":"ঘোড়াঘাট","nameEn":"Ghoraghat"},
    {"id":"407","nameBn":"বিরামপুর","nameEn":"Birampur"},
    {"id":"408","nameBn":"পার্বতীপুর","nameEn":"Parbatipur"},
    {"id":"409","nameBn":"বোচাগঞ্জ","nameEn":"Bochaganj"},
    {"id":"410","nameBn":"কাহারোল","nameEn":"Kaharol"},
    {"id":"411","nameBn":"ফুলবাড়ী","nameEn":"Fulbari"},
    {"id":"412","nameBn":"দিনাজপুর সদর","nameEn":"Dinajpur Sadar"},
    {"id":"413","nameBn":"হাকিমপুর","nameEn":"Hakimpur"},
    {"id":"414","nameBn":"খানসামা","nameEn":"Khansama"},
    {"id":"415","nameBn":"বিরল","nameEn":"Birol"},
    {"id":"416","nameBn":"চিরিরবন্দর","nameEn":"Chirirbandar"},
  ],
  "55": [
    {"id":"417","nameBn":"লালমনিরহাট সদর","nameEn":"Lalmonirhat Sadar"},
    {"id":"418","nameBn":"কালীগঞ্জ","nameEn":"Kaliganj"},
    {"id":"419","nameBn":"হাতীবান্ধা","nameEn":"Hatibandha"},
    {"id":"420","nameBn":"পাটগ্রাম","nameEn":"Patgram"},
    {"id":"421","nameBn":"আদিতমারী","nameEn":"Aditmari"},
  ],
  "56": [
    {"id":"422","nameBn":"সৈয়দপুর","nameEn":"Syedpur"},
    {"id":"423","nameBn":"ডোমার","nameEn":"Domar"},
    {"id":"424","nameBn":"ডিমলা","nameEn":"Dimla"},
    {"id":"425","nameBn":"জলঢাকা","nameEn":"Jaldhaka"},
    {"id":"426","nameBn":"কিশোরগঞ্জ","nameEn":"Kishorganj"},
    {"id":"427","nameBn":"নীলফামারী সদর","nameEn":"Nilphamari Sadar"},
  ],
  "57": [
    {"id":"428","nameBn":"সাদুল্লাপুর","nameEn":"Sadullapur"},
    {"id":"429","nameBn":"গাইবান্ধা সদর","nameEn":"Gaibandha Sadar"},
    {"id":"430","nameBn":"পলাশবাড়ী","nameEn":"Palashbari"},
    {"id":"431","nameBn":"সাঘাটা","nameEn":"Saghata"},
    {"id":"432","nameBn":"গোবিন্দগঞ্জ","nameEn":"Gobindaganj"},
    {"id":"433","nameBn":"সুন্দরগঞ্জ","nameEn":"Sundarganj"},
    {"id":"434","nameBn":"ফুলছড়ি","nameEn":"Phulchari"},
  ],
  "58": [
    {"id":"435","nameBn":"ঠাকুরগাঁও সদর","nameEn":"Thakurgaon Sadar"},
    {"id":"436","nameBn":"পীরগঞ্জ","nameEn":"Pirganj"},
    {"id":"437","nameBn":"রাণীশংকৈল","nameEn":"Ranisankail"},
    {"id":"438","nameBn":"হরিপুর","nameEn":"Haripur"},
    {"id":"439","nameBn":"বালিয়াডাঙ্গী","nameEn":"Baliadangi"},
  ],
  "59": [
    {"id":"440","nameBn":"রংপুর সদর","nameEn":"Rangpur Sadar"},
    {"id":"441","nameBn":"গংগাচড়া","nameEn":"Gangachara"},
    {"id":"442","nameBn":"তারাগঞ্জ","nameEn":"Taragonj"},
    {"id":"443","nameBn":"বদরগঞ্জ","nameEn":"Badargonj"},
    {"id":"444","nameBn":"মিঠাপুকুর","nameEn":"Mithapukur"},
    {"id":"445","nameBn":"পীরগঞ্জ","nameEn":"Pirgonj"},
    {"id":"446","nameBn":"কাউনিয়া","nameEn":"Kaunia"},
    {"id":"447","nameBn":"পীরগাছা","nameEn":"Pirgacha"},
  ],
  "60": [
    {"id":"448","nameBn":"কুড়িগ্রাম সদর","nameEn":"Kurigram Sadar"},
    {"id":"449","nameBn":"নাগেশ্বরী","nameEn":"Nageshwari"},
    {"id":"450","nameBn":"ভুরুঙ্গামারী","nameEn":"Bhurungamari"},
    {"id":"451","nameBn":"ফুলবাড়ী","nameEn":"Phulbari"},
    {"id":"452","nameBn":"রাজারহাট","nameEn":"Rajarhat"},
    {"id":"453","nameBn":"উলিপুর","nameEn":"Ulipur"},
    {"id":"454","nameBn":"চিলমারী","nameEn":"Chilmari"},
    {"id":"455","nameBn":"রৌমারী","nameEn":"Rowmari"},
    {"id":"456","nameBn":"চর রাজিবপুর","nameEn":"Charrajibpur"},
  ],
  "61": [
    {"id":"457","nameBn":"শেরপুর সদর","nameEn":"Sherpur Sadar"},
    {"id":"458","nameBn":"নালিতাবাড়ী","nameEn":"Nalitabari"},
    {"id":"459","nameBn":"শ্রীবরদী","nameEn":"Sreebordi"},
    {"id":"460","nameBn":"নকলা","nameEn":"Nokla"},
    {"id":"461","nameBn":"ঝিনাইগাতী","nameEn":"Jhenaigati"},
  ],
  "62": [
    {"id":"462","nameBn":"ফুলবাড়ীয়া","nameEn":"Fulbaria"},
    {"id":"463","nameBn":"ত্রিশাল","nameEn":"Trishal"},
    {"id":"464","nameBn":"ভালুকা","nameEn":"Bhaluka"},
    {"id":"465","nameBn":"মুক্তাগাছা","nameEn":"Muktagacha"},
    {"id":"466","nameBn":"ময়মনসিংহ সদর","nameEn":"Mymensingh Sadar"},
    {"id":"467","nameBn":"ধোবাউড়া","nameEn":"Dhobaura"},
    {"id":"468","nameBn":"ফুলপুর","nameEn":"Phulpur"},
    {"id":"469","nameBn":"হালুয়াঘাট","nameEn":"Haluaghat"},
    {"id":"470","nameBn":"গৌরীপুর","nameEn":"Gouripur"},
    {"id":"471","nameBn":"গফরগাঁও","nameEn":"Gafargaon"},
    {"id":"472","nameBn":"ঈশ্বরগঞ্জ","nameEn":"Iswarganj"},
    {"id":"473","nameBn":"নান্দাইল","nameEn":"Nandail"},
    {"id":"474","nameBn":"তারাকান্দা","nameEn":"Tarakanda"},
  ],
  "63": [
    {"id":"475","nameBn":"জামালপুর সদর","nameEn":"Jamalpur Sadar"},
    {"id":"476","nameBn":"মেলান্দহ","nameEn":"Melandah"},
    {"id":"477","nameBn":"ইসলামপুর","nameEn":"Islampur"},
    {"id":"478","nameBn":"দেওয়ানগঞ্জ","nameEn":"Dewangonj"},
    {"id":"479","nameBn":"সরিষাবাড়ী","nameEn":"Sarishabari"},
    {"id":"480","nameBn":"মাদারগঞ্জ","nameEn":"Madarganj"},
    {"id":"481","nameBn":"বকশীগঞ্জ","nameEn":"Bokshiganj"},
  ],
  "64": [
    {"id":"482","nameBn":"বারহাট্টা","nameEn":"Barhatta"},
    {"id":"483","nameBn":"দুর্গাপুর","nameEn":"Durgapur"},
    {"id":"484","nameBn":"কেন্দুয়া","nameEn":"Kendua"},
    {"id":"485","nameBn":"আটপাড়া","nameEn":"Atpara"},
    {"id":"486","nameBn":"মদন","nameEn":"Madan"},
    {"id":"487","nameBn":"খালিয়াজুরী","nameEn":"Khaliajuri"},
    {"id":"488","nameBn":"কলমাকান্দা","nameEn":"Kalmakanda"},
    {"id":"489","nameBn":"মোহনগঞ্জ","nameEn":"Mohongonj"},
    {"id":"490","nameBn":"পূর্বধলা","nameEn":"Purbadhala"},
    {"id":"491","nameBn":"নেত্রকোণা সদর","nameEn":"Netrokona Sadar"},
  ],
};

export function getUpazilas(districtId: string): LocationOption[] {
  return UPAZILAS_BY_DISTRICT[districtId] ?? [];
}

function normalizeSearchText(value: string): string {
  return value.normalize("NFKC").trim().toLocaleLowerCase("en");
}

export function searchLocations(
  options: LocationOption[],
  query: string,
): LocationOption[] {
  const normalizedQuery = normalizeSearchText(query);

  if (!normalizedQuery) {
    return options;
  }

  return options.filter((option) =>
    normalizeSearchText(`${option.nameBn} ${option.nameEn}`).includes(
      normalizedQuery,
    ),
  );
}
